name: Deploy

on:

  push:
    branches: [ main ]

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    uses: ./.github/workflows/build.yml

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-build

      - name: Copy artifact via ssh connection
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          source: ${{ github.sha }}.tar.gz
          target: ${{ secrets.PATH }}
          debug: true
          rm: true
        
      - name: Untar the artifact
        uses: appleboy/ssh-action@v1.0.3
        env:
          APP_PATH: ${{ secrets.PATH }}
          COMMIT_SHA: ${{ github.sha }}
        with:          
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: APP_PATH, COMMIT_SHA
          script: |
            cd $APP_PATH
            tar -xvf ${COMMIT_SHA}.tar.gz -C . --strip-components=1
            rm ${COMMIT_SHA}.tar.gz
